<?php

namespace Modules\Helper\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use DB;

/**
 * Class HelperDatabaseSeeder
 *
 * The Seeder is Defined for languages, Currency and Locals.
 *
 * PHP version 7.1.3
 *
 * @category  Helper
 * @package   Modules\Helper
 * @author    Vipul Patel <vipul@chetsapp.com>
 * @copyright 2019 Chetsapp Group
 * @license   Chetsapp Private Limited
 * @version   Release: @1.0@
 * @link      http://chetsapp.com
 * @since     Class available since Release 1.0
 */
class HelperDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        // --
        // Insert Languages
        DB::table(config('core.acl.languages_table'))->truncate();
        $data = [
            ['id' => 1, 'code' => 'ar', 'name' => 'Arabic'],
            ['id' => 2, 'code' => 'cs', 'name' => 'Czech'],
            ['id' => 3, 'code' => 'da', 'name' => 'Danish'],
            ['id' => 4, 'code' => 'de', 'name' => 'German'],
            ['id' => 5, 'code' => 'el', 'name' => 'Greek'],
            ['id' => 6, 'code' => 'en', 'name' => 'English'],
            ['id' => 7, 'code' => 'es', 'name' => 'Spanish'],
            ['id' => 8, 'code' => 'fr', 'name' => 'French'],
            ['id' => 9, 'code' => 'gu', 'name' => 'Gujarati'],
            ['id' => 10, 'code' => 'hi', 'name' => 'Hindi'],
            ['id' => 11, 'code' => 'id', 'name' => 'Indonesian'],
            ['id' => 12, 'code' => 'it', 'name' => 'Italian'],
            ['id' => 13, 'code' => 'ja', 'name' => 'Japanese'],
            ['id' => 14, 'code' => 'nl', 'name' => 'Dutch'],
            ['id' => 15, 'code' => 'no', 'name' => 'Norwegian'],
            ['id' => 16, 'code' => 'pl', 'name' => 'Polish'],
            ['id' => 17, 'code' => 'pt', 'name' => 'Portuguese'],
            ['id' => 18, 'code' => 'ro', 'name' => 'Romanian'],
            ['id' => 19, 'code' => 'ru', 'name' => 'Russian'],
            ['id' => 20, 'code' => 'tr', 'name' => 'Turkish'],
            ['id' => 21, 'code' => 'zh', 'name' => 'Chinese'],
        ];
        DB::table(config('core.acl.languages_table'))->insert($data);

        // --
        // Insert Currency
        DB::table(config('core.acl.currency'))->truncate();
        $data = [
            ['id' => 1, 'code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$'],
            ['id' => 2, 'code' => 'BDT', 'name' => 'Bangladesh', 'symbol' => '৳'],
            ['id' => 3, 'code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$'],
            ['id' => 4, 'code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$'],
            ['id' => 5, 'code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'Fr.'],
            ['id' => 6, 'code' => 'CLP', 'name' => 'Chilean Peso', 'symbol' => '$'],
            ['id' => 7, 'code' => 'CNY', 'name' => 'Chinese Yuan', 'symbol' => '¥'],
            ['id' => 8, 'code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč'],
            ['id' => 9, 'code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr.'],
            ['id' => 10, 'code' => 'EUR', 'name' => 'Euro', 'symbol' => '€'],
            ['id' => 11, 'code' => 'GBP', 'name' => 'British Pound', 'symbol' => '£'],
            ['id' => 12, 'code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => '$'],
            ['id' => 13, 'code' => 'HUF', 'name' => 'Hungarian Forint', 'symbol' => 'Ft'],
            ['id' => 14, 'code' => 'IDR', 'name' => 'Indonesian Rupiah', 'symbol' => 'Rp'],
            ['id' => 15, 'code' => 'ILS', 'name' => 'Israeli New Shekel', 'symbol' => '₪'],
            ['id' => 16, 'code' => 'INR', 'name' => 'Indian Rupee', 'symbol' => '₹'],
            ['id' => 17, 'code' => 'JPY', 'name' => 'Japanese Yen', 'symbol' => '¥'],
            ['id' => 18, 'code' => 'KRW', 'name' => 'Korean Won', 'symbol' => '₩'],
            ['id' => 19, 'code' => 'MXN', 'name' => 'Mexican Peso', 'symbol' => '$'],
            ['id' => 20, 'code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
            ['id' => 21, 'code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr'],
            ['id' => 22, 'code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$'],
            ['id' => 23, 'code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => '₱'],
            ['id' => 24, 'code' => 'PKR', 'name' => 'Pakistan Rupee', 'symbol' => '₨'],
            ['id' => 25, 'code' => 'PLN', 'name' => 'Polish Zloty', 'symbol' => 'zł'],
            ['id' => 26, 'code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => 'RUB'],
            ['id' => 27, 'code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr'],
            ['id' => 28, 'code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$'],
            ['id' => 29, 'code' => 'THB', 'name' => 'Thai Baht', 'symbol' => '฿'],
            ['id' => 30, 'code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => '₺'],
            ['id' => 31, 'code' => 'TWD', 'name' => 'Taiwan Dollar', 'symbol' => '$'],
            ['id' => 32, 'code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$'],
            ['id' => 33, 'code' => 'VEF', 'name' => 'Bolívar Fuerte', 'symbol' => 'Bs.'],
            ['id' => 34, 'code' => 'ZAR', 'name' => 'South African Rand', 'symbol' => 'R']
        ];
        DB::table(config('core.acl.currency'))->insert($data);

        // --
        // Insert Locals
        DB::table(config('core.acl.locales_table'))->truncate();
        $data = [
            ['id' => 1, 'name' => 'Afghanistan', 'locale' => 'afghanistan'],
            ['id' => 2, 'name' => 'Aringland Islands', 'locale' => 'aringland_islands'],
            ['id' => 3, 'name' => 'Albania', 'locale' => 'albania'],
            ['id' => 4, 'name' => 'Algeria', 'locale' => 'algeria'],
            ['id' => 5, 'name' => 'American Samoa', 'locale' => 'american_samoa'],
            ['id' => 6, 'name' => 'Andorra', 'locale' => 'andorra'],
            ['id' => 7, 'name' => 'Angola', 'locale' => 'angola'],
            ['id' => 8, 'name' => 'Anguilla', 'locale' => 'anguilla'],
            ['id' => 9, 'name' => 'Antarctica', 'locale' => 'antarctica'],
            ['id' => 10, 'name' => 'Antigua and Barbuda', 'locale' => 'antigua_and_barbuda'],
            ['id' => 11, 'name' => 'Argentina', 'locale' => 'argentina'],
            ['id' => 12, 'name' => 'Armenia', 'locale' => 'armenia'],
            ['id' => 13, 'name' => 'Aruba', 'locale' => 'aruba'],
            ['id' => 14, 'name' => 'Australia', 'locale' => 'australia'],
            ['id' => 15, 'name' => 'Austria', 'locale' => 'austria'],
            ['id' => 16, 'name' => 'Azerbaijan', 'locale' => 'azerbaijan'],
            ['id' => 17, 'name' => 'Bahamas', 'locale' => 'bahamas'],
            ['id' => 18, 'name' => 'Bahrain', 'locale' => 'bahrain'],
            ['id' => 19, 'name' => 'Bangladesh', 'locale' => 'bangladesh'],
            ['id' => 20, 'name' => 'Barbados', 'locale' => 'barbados'],
            ['id' => 21, 'name' => 'Belarus', 'locale' => 'belarus'],
            ['id' => 22, 'name' => 'Belgium', 'locale' => 'belgium'],
            ['id' => 23, 'name' => 'Belize', 'locale' => 'belize'],
            ['id' => 24, 'name' => 'Benin', 'locale' => 'benin'],
            ['id' => 25, 'name' => 'Bermuda', 'locale' => 'bermuda'],
            ['id' => 26, 'name' => 'Bhutan', 'locale' => 'bhutan'],
            ['id' => 27, 'name' => 'Bolivia', 'locale' => 'bolivia'],
            ['id' => 28, 'name' => 'Bosnia and Herzegovina', 'locale' => 'bosnia_and_herzegovina'],
            ['id' => 29, 'name' => 'Botswana', 'locale' => 'botswana'],
            ['id' => 30, 'name' => 'Bouvet Island', 'locale' => 'bouvet_island'],
            ['id' => 31, 'name' => 'Brazil', 'locale' => 'brazil'],
            ['id' => 32, 'name' => 'British Indian Ocean territory', 'locale' => 'british_indian_ocean_territory'],
            ['id' => 33, 'name' => 'Brunei Darussalam', 'locale' => 'brunei_darussalam'],
            ['id' => 34, 'name' => 'Bulgaria', 'locale' => 'bulgaria'],
            ['id' => 35, 'name' => 'Burkina Faso', 'locale' => 'burkina_faso'],
            ['id' => 36, 'name' => 'Burundi', 'locale' => 'burundi'],
            ['id' => 37, 'name' => 'Cambodia', 'locale' => 'cambodia'],
            ['id' => 38, 'name' => 'Cameroon', 'locale' => 'cameroon'],
            ['id' => 39, 'name' => 'Canada', 'locale' => 'canada'],
            ['id' => 40, 'name' => 'Cape Verde', 'locale' => 'cape_verde'],
            ['id' => 41, 'name' => 'Cayman Islands', 'locale' => 'cayman_islands'],
            ['id' => 42, 'name' => 'Central African Republic', 'locale' => 'central_african_republic'],
            ['id' => 43, 'name' => 'Chad', 'locale' => 'chad'],
            ['id' => 44, 'name' => 'Chile', 'locale' => 'chile'],
            ['id' => 45, 'name' => 'China', 'locale' => 'china'],
            ['id' => 46, 'name' => 'Christmas Island', 'locale' => 'christmas_island'],
            ['id' => 47, 'name' => 'Cocos(Keeling) Islands', 'locale' => 'cocos_islands'],
            ['id' => 48, 'name' => 'Colombia', 'locale' => 'colombia'],
            ['id' => 49, 'name' => 'Comoros', 'locale' => 'comoros'],
            ['id' => 50, 'name' => 'Congo', 'locale' => 'congo'],
            ['id' => 51, 'name' => 'Democratic Republic', 'locale' => 'democratic_republic'],
            ['id' => 52, 'name' => 'Cook Islands', 'locale' => 'cook_islands'],
            ['id' => 53, 'name' => 'Costa Rica', 'locale' => 'costa_rica'],
            ['id' => 54, 'name' => 'Ivory Coast(Ivory Coast)', 'locale' => 'ivory_coast'],
            ['id' => 55, 'name' => 'Croatia(Hrvatska)', 'locale' => 'croatia'],
            ['id' => 56, 'name' => 'Cuba', 'locale' => 'cuba'],
            ['id' => 57, 'name' => 'Cyprus', 'locale' => 'cyprus'],
            ['id' => 58, 'name' => 'Czech Republic', 'locale' => 'czech_republic'],
            ['id' => 59, 'name' => 'Denmark', 'locale' => 'denmark'],
            ['id' => 60, 'name' => 'Djibouti', 'locale' => 'djibouti'],
            ['id' => 61, 'name' => 'Dominica', 'locale' => 'dominica'],
            ['id' => 62, 'name' => 'Dominican Republic', 'locale' => 'dominican_republic'],
            ['id' => 63, 'name' => 'East Timor', 'locale' => 'east_timor'],
            ['id' => 64, 'name' => 'Ecuador', 'locale' => 'ecuador'],
            ['id' => 65, 'name' => 'Egypt', 'locale' => 'egypt'],
            ['id' => 66, 'name' => 'El Salvador', 'locale' => 'el_salvador'],
            ['id' => 67, 'name' => 'Equatorial Guinea', 'locale' => 'equatorial_guinea'],
            ['id' => 68, 'name' => 'Eritrea', 'locale' => 'eritrea'],
            ['id' => 69, 'name' => 'Estonia', 'locale' => 'estonia'],
            ['id' => 70, 'name' => 'Ethiopia', 'locale' => 'ethiopia'],
            ['id' => 71, 'name' => 'Falkland Islands', 'locale' => 'falkland_islands'],
            ['id' => 72, 'name' => 'Faroe Islands', 'locale' => 'faroe_islands'],
            ['id' => 73, 'name' => 'Fiji', 'locale' => 'fiji'],
            ['id' => 74, 'name' => 'Finland', 'locale' => 'finland'],
            ['id' => 75, 'name' => 'France', 'locale' => 'france'],
            ['id' => 76, 'name' => 'French Guiana', 'locale' => 'french_guiana'],
            ['id' => 77, 'name' => 'French Polynesia', 'locale' => 'french_polynesia'],
            ['id' => 78, 'name' => 'French Southern Territories', 'locale' => 'french_southern_territories'],
            ['id' => 79, 'name' => 'Gabon', 'locale' => 'gabon'],
            ['id' => 80, 'name' => 'Gambia', 'locale' => 'gambia'],
            ['id' => 81, 'name' => 'Georgia', 'locale' => 'georgia'],
            ['id' => 82, 'name' => 'Germany', 'locale' => 'germany'],
            ['id' => 83, 'name' => 'Ghana', 'locale' => 'ghana'],
            ['id' => 84, 'name' => 'Gibraltar', 'locale' => 'gibraltar'],
            ['id' => 85, 'name' => 'Greece', 'locale' => 'greece'],
            ['id' => 86, 'name' => 'Greenland', 'locale' => 'greenland'],
            ['id' => 87, 'name' => 'Grenada', 'locale' => 'grenada'],
            ['id' => 88, 'name' => 'Guadeloupe', 'locale' => 'guadeloupe'],
            ['id' => 89, 'name' => 'Guam', 'locale' => 'guam'],
            ['id' => 90, 'name' => 'Guatemala', 'locale' => 'guatemala'],
            ['id' => 91, 'name' => 'Guinea', 'locale' => 'guinea'],
            ['id' => 92, 'name' => 'Guinea-Bissau', 'locale' => 'guinea_bissau'],
            ['id' => 93, 'name' => 'Guyana', 'locale' => 'guyana'],
            ['id' => 94, 'name' => 'Haiti', 'locale' => 'haiti'],
            ['id' => 95, 'name' => 'Heard and McDonald Islands', 'locale' => 'heard_and_mcdonald_islands'],
            ['id' => 96, 'name' => 'Honduras', 'locale' => 'honduras'],
            ['id' => 97, 'name' => 'Hong Kong', 'locale' => 'hong_kong'],
            ['id' => 98, 'name' => 'Hungary', 'locale' => 'hungary'],
            ['id' => 99, 'name' => 'Iceland', 'locale' => 'iceland'],
            ['id' => 100, 'name' => 'India', 'locale' => 'india'],
            ['id' => 101, 'name' => 'Indonesia', 'locale' => 'indonesia'],
            ['id' => 102, 'name' => 'Iran', 'locale' => 'iran'],
            ['id' => 103, 'name' => 'Iraq', 'locale' => 'iraq'],
            ['id' => 104, 'name' => 'Ireland', 'locale' => 'ireland'],
            ['id' => 105, 'name' => 'Israel', 'locale' => 'israel'],
            ['id' => 106, 'name' => 'Italy', 'locale' => 'italy'],
            ['id' => 107, 'name' => 'Jamaica', 'locale' => 'jamaica'],
            ['id' => 108, 'name' => 'Japan', 'locale' => 'japan'],
            ['id' => 109, 'name' => 'Jordan', 'locale' => 'jordan'],
            ['id' => 110, 'name' => 'Kazakhstan', 'locale' => 'kazakhstan'],
            ['id' => 111, 'name' => 'Kenya', 'locale' => 'kenya'],
            ['id' => 112, 'name' => 'Kiribati', 'locale' => 'kiribati'],
            ['id' => 113, 'name' => 'Korea (north)', 'locale' => 'korea_north'],
            ['id' => 114, 'name' => 'Korea (south)', 'locale' => 'korea_south'],
            ['id' => 115, 'name' => 'Kuwait', 'locale' => 'kuwait'],
            ['id' => 116, 'name' => 'Kyrgyzstan', 'locale' => 'kyrgyzstan'],
            ['id' => 117, 'name' => 'Lao People\'s Democratic Republic', 'locale' => 'Lao_peoples_emocratic_republic'],
            ['id' => 118, 'name' => 'Latvia', 'locale' => 'latvia'],
            ['id' => 119, 'name' => 'Lebanon', 'locale' => 'lebanon'],
            ['id' => 120, 'name' => 'Lesotho', 'locale' => 'lesotho'],
            ['id' => 121, 'name' => 'Liberia', 'locale' => 'liberia'],
            ['id' => 122, 'name' => 'Libyan Arab Jamahiriya', 'locale' => 'libyan_arab_jamahiriya'],
            ['id' => 123, 'name' => 'Liechtenstein', 'locale' => 'liechtenstein'],
            ['id' => 124, 'name' => 'Lithuania', 'locale' => 'lithuania'],
            ['id' => 125, 'name' => 'Luxembourg', 'locale' => 'luxembourg'],
            ['id' => 126, 'name' => 'Macao', 'locale' => 'macao'],
            ['id' => 127, 'name' => 'Macedonia', 'locale' => 'macedonia'],
            ['id' => 128, 'name' => 'Madagascar', 'locale' => 'madagascar'],
            ['id' => 129, 'name' => 'Malawi', 'locale' => 'malawi'],
            ['id' => 130, 'name' => 'Malaysia', 'locale' => 'malaysia'],
            ['id' => 131, 'name' => 'Maldives', 'locale' => 'maldives'],
            ['id' => 132, 'name' => 'Mali', 'locale' => 'mali'],
            ['id' => 133, 'name' => 'Malta', 'locale' => 'malta'],
            ['id' => 134, 'name' => 'Marshall Islands', 'locale' => 'marshall_islands'],
            ['id' => 135, 'name' => 'Martinique', 'locale' => 'martinique'],
            ['id' => 136, 'name' => 'Mauritania', 'locale' => 'mauritania'],
            ['id' => 137, 'name' => 'Mauritius', 'locale' => 'mauritius'],
            ['id' => 138, 'name' => 'Mayotte', 'locale' => 'mayotte'],
            ['id' => 139, 'name' => 'Mexico', 'locale' => 'mexico'],
            ['id' => 140, 'name' => 'Micronesia', 'locale' => 'micronesia'],
            ['id' => 141, 'name' => 'Moldova', 'locale' => 'moldova'],
            ['id' => 142, 'name' => 'Monaco', 'locale' => 'monaco'],
            ['id' => 143, 'name' => 'Mongolia', 'locale' => 'mongolia'],
            ['id' => 144, 'name' => 'Montserrat', 'locale' => 'Montserrat'],
            ['id' => 145, 'name' => 'Morocco', 'locale' => 'morocco'],
            ['id' => 146, 'name' => 'Mozambique', 'locale' => 'mozambique'],
            ['id' => 147, 'name' => 'Myanmar', 'locale' => 'myanmar'],
            ['id' => 148, 'name' => 'Namibia', 'locale' => 'namibia'],
            ['id' => 149, 'name' => 'Nauru', 'locale' => 'nauru'],
            ['id' => 150, 'name' => 'Nepal', 'locale' => 'nepal'],
            ['id' => 151, 'name' => 'Netherlands', 'locale' => 'netherlands'],
            ['id' => 152, 'name' => 'Netherlands Antilles', 'locale' => 'netherlands_antilles'],
            ['id' => 153, 'name' => 'New Caledonia', 'locale' => 'new_caledonia'],
            ['id' => 154, 'name' => 'New Zealand', 'locale' => 'new_zealand'],
            ['id' => 155, 'name' => 'Nicaragua', 'locale' => 'nicaragua'],
            ['id' => 156, 'name' => 'Niger', 'locale' => 'niger'],
            ['id' => 157, 'name' => 'Nigeria', 'locale' => 'nigeria'],
            ['id' => 158, 'name' => 'Niue', 'locale' => 'niue'],
            ['id' => 159, 'name' => 'Norfolk Island', 'locale' => 'norfolk_island'],
            ['id' => 160, 'name' => 'Northern Mariana Islands', 'locale' => 'northern_mariana_islands'],
            ['id' => 161, 'name' => 'Norway', 'locale' => 'norway'],
            ['id' => 162, 'name' => 'Oman', 'locale' => 'oman'],
            ['id' => 163, 'name' => 'Pakistan', 'locale' => 'pakistan'],
            ['id' => 164, 'name' => 'Palau', 'locale' => 'palau'],
            ['id' => 165, 'name' => 'Palestinian Territories', 'locale' => 'palestinian_territories'],
            ['id' => 166, 'name' => 'Panama', 'locale' => 'panama'],
            ['id' => 167, 'name' => 'Papua New Guinea', 'locale' => 'papua_new_guinea'],
            ['id' => 168, 'name' => 'Paraguay', 'locale' => 'paraguay'],
            ['id' => 169, 'name' => 'Peru', 'locale' => 'peru'],
            ['id' => 170, 'name' => 'Philippines', 'locale' => 'philippines'],
            ['id' => 171, 'name' => 'Pitcairn', 'locale' => 'pitcairn'],
            ['id' => 172, 'name' => 'Poland', 'locale' => 'poland'],
            ['id' => 173, 'name' => 'Portugal', 'locale' => 'portugal'],
            ['id' => 174, 'name' => 'Puerto Rico', 'locale' => 'puerto_rico'],
            ['id' => 175, 'name' => 'Qatar', 'locale' => 'qatar'],
            ['id' => 176, 'name' => 'Runion', 'locale' => 'runion'],
            ['id' => 177, 'name' => 'Romania', 'locale' => 'romania'],
            ['id' => 178, 'name' => 'Russian Federation', 'locale' => 'russian_federation'],
            ['id' => 179, 'name' => 'Rwanda', 'locale' => 'rwanda'],
            ['id' => 180, 'name' => 'Saint Helena', 'locale' => 'saint_helena'],
            ['id' => 181, 'name' => 'Saint Kitts and Nevis', 'locale' => 'saint_kitts_and_nevis'],
            ['id' => 182, 'name' => 'Saint Lucia', 'locale' => 'saint_lucia'],
            ['id' => 183, 'name' => 'Saint Pierre and Miquelon', 'locale' => 'saint_pierre_and_miquelon'],
            ['id' => 184, 'name' => 'Saint Vincent and the Grenadines', 'locale' => 'saint_vincent_and_the_grenadines'],
            ['id' => 185, 'name' => 'Samoa', 'locale' => 'samoa'],
            ['id' => 186, 'name' => 'San Marino', 'locale' => 'san_marino'],
            ['id' => 187, 'name' => 'Sao Tome and Principe', 'locale' => 'sao_tome_and_principe'],
            ['id' => 188, 'name' => 'Saudi Arabia', 'locale' => 'saudi_arabia'],
            ['id' => 189, 'name' => 'Senegal', 'locale' => 'senegal'],
            ['id' => 190, 'name' => 'Serbia and Montenegro', 'locale' => 'serbia_and_montenegro'],
            ['id' => 191, 'name' => 'Seychelles', 'locale' => 'seychelles'],
            ['id' => 192, 'name' => 'Sierra Leone', 'locale' => 'sierra_leone'],
            ['id' => 193, 'name' => 'Singapore', 'locale' => 'singapore'],
            ['id' => 194, 'name' => 'Slovakia', 'locale' => 'slovakia'],
            ['id' => 195, 'name' => 'Slovenia', 'locale' => 'slovenia'],
            ['id' => 196, 'name' => 'Solomon Islands', 'locale' => 'solomon_islands'],
            ['id' => 197, 'name' => 'Somalia', 'locale' => 'somalia'],
            ['id' => 198, 'name' => 'South Africa', 'locale' => 'south_africa'],
            ['id' => 199, 'name' => 'South Georgia and the South Sandwich Islands', 'locale' => 'south_georgia_and_the_south_sandwich_islands'],
            ['id' => 200, 'name' => 'Spain', 'locale' => 'spain'],
            ['id' => 201, 'name' => 'Sri Lanka', 'locale' => 'sri_lanka'],
            ['id' => 202, 'name' => 'Sudan', 'locale' => 'sudan'],
            ['id' => 203, 'name' => 'Suriname', 'locale' => 'suriname'],
            ['id' => 204, 'name' => 'Svalbard and Jan Mayen Islands', 'locale' => 'svalbard_and_jan_mayen_islands'],
            ['id' => 205, 'name' => 'Swaziland', 'locale' => 'swaziland'],
            ['id' => 206, 'name' => 'Sweden', 'locale' => 'sweden'],
            ['id' => 207, 'name' => 'Switzerland', 'locale' => 'switzerland'],
            ['id' => 208, 'name' => 'Syria', 'locale' => 'syria'],
            ['id' => 209, 'name' => 'Taiwan', 'locale' => 'taiwan'],
            ['id' => 210, 'name' => 'Tajikistan', 'locale' => 'tajikistan'],
            ['id' => 211, 'name' => 'Tanzania', 'locale' => 'tanzania'],
            ['id' => 212, 'name' => 'Thailand', 'locale' => 'thailand'],
            ['id' => 213, 'name' => 'Togo', 'locale' => 'togo'],
            ['id' => 214, 'name' => 'Tokelau', 'locale' => 'tokelau'],
            ['id' => 215, 'name' => 'Tonga', 'locale' => 'tonga'],
            ['id' => 216, 'name' => 'Trinidad and Tobago', 'locale' => 'trinidad_and_tobago'],
            ['id' => 217, 'name' => 'Tunisia', 'locale' => 'tunisia'],
            ['id' => 218, 'name' => 'Turkey', 'locale' => 'turkey'],
            ['id' => 219, 'name' => 'Turkmenistan', 'locale' => 'turkmenistan'],
            ['id' => 220, 'name' => 'Turks and Caicos Islands', 'locale' => 'turks_and_caicos_islands'],
            ['id' => 221, 'name' => 'Tuvalu', 'locale' => 'tuvalu'],
            ['id' => 222, 'name' => 'Uganda', 'locale' => 'uganda'],
            ['id' => 223, 'name' => 'Ukraine', 'locale' => 'ukraine'],
            ['id' => 224, 'name' => 'United Arab Emirates', 'locale' => 'united_arab_emirates'],
            ['id' => 225, 'name' => 'United Kingdom', 'locale' => 'united_kingdom'],
            ['id' => 226, 'name' => 'United States of America', 'locale' => 'united_states_of_america'],
            ['id' => 227, 'name' => 'Uruguay', 'locale' => 'uruguay'],
            ['id' => 228, 'name' => 'Uzbekistan', 'locale' => 'uzbekistan'],
            ['id' => 229, 'name' => 'Vanuatu', 'locale' => 'vanuatu'],
            ['id' => 230, 'name' => 'Vatican City', 'locale' => 'vatican_city'],
            ['id' => 231, 'name' => 'Venezuela', 'locale' => 'venezuela'],
            ['id' => 232, 'name' => 'Vietnam', 'locale' => 'vietnam'],
            ['id' => 233, 'name' => 'Virgin Islands (British)', 'locale' => 'virgin_islands_british'],
            ['id' => 234, 'name' => 'Virgin Islands (US)', 'locale' => 'virgin_islands_us'],
            ['id' => 235, 'name' => 'Wallis and Futuna Islands', 'locale' => 'wallis_and_futuna_islands'],
            ['id' => 236, 'name' => 'Western Sahara', 'locale' => 'western_sahara'],
            ['id' => 237, 'name' => 'Yemen', 'locale' => 'yemen'],
            ['id' => 238, 'name' => 'Zaire', 'locale' => 'zaire'],
            ['id' => 239, 'name' => 'Zambia', 'locale' => 'zambia'],
            ['id' => 240, 'name' => 'Zimbabwe', 'locale' => 'zimbabwe']
        ];
        DB::table(config('core.acl.locales_table'))->insert($data);

        // --
        // Insert Modules.
        DB::table(config('core.acl.modules_table'))->truncate();
        $data = [
            ['module_id' => 1, 'module_name' => 'Project', 'module_slug' => 'projects'],
            ['module_id' => 2, 'module_name' => 'Task', 'module_slug' => 'task'],
            ['module_id' => 3, 'module_name' => 'Defect', 'module_slug' => 'defect'],
            ['module_id' => 4, 'module_name' => 'Incident', 'module_slug' => 'incident'],
            ['module_id' => 5, 'module_name' => 'Meeting', 'module_slug' => 'meeting'],
            ['module_id' => 6, 'module_name' => 'Other', 'module_slug' => 'other'],
            ['module_id' => 7, 'module_name' => 'Leave', 'module_slug' => 'leave']
        ];
        DB::table(config('core.acl.modules_table'))->insert($data);
    }
}
